apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mirakurun
  namespace: epg
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: mydnschallenge
  routes:
    - match: Host(`m.doany.io`)
      kind: Rule
      priority: 50
      middlewares:
        - name: forward-auth-errors
          namespace: auth
        - name: forward-auth
          namespace: auth
      services:
        - name: mirakurun
          port: 40772
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: epg
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: denpa
  namespace: epg
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: mydnschallenge
  routes:
    - match: Host(`dp.doany.io`)
      kind: Rule
      priority: 50
      middlewares:
        - name: forward-auth
          namespace: auth
      services:
        - name: denpa
          port: 3000
