---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: epgstation-secrets
  namespace: epg
spec:
  encryptedData:
    xool-api-key: AgBWdvyTAdXtP/xOutu1jKzS+/o3x7VaatfmCf0PgCrN5YoX/k7HpjZY+YC7iL0pV2CU8bQ82BB3OW1JVB6j75YW2292nfS9roZGGI6lptaHJrVT0mpAYRr170TSADKvlqukiPcNmYLo33FUL/OgNOvjf3uoazi0Xw8LW2upyKIuC57Sbg3rphNWL+RhIlqavOaijNdFqTadvPh8+C3LRGLKSUAvkcJD/WLMf9mflxTybADYpetLer0zPTpcLb4OFZ6ghRwoq4wCsJt1Rvt0qw567Pi81qm8Vx+NmrtdwBIZ05C+U4wj1HtDbkEWZoQ7BGvbv7gvz372pcrFo1CNP+aZVb6KtaVz3pwfu+rZfgcx5dcWJBkZNeJuypFv1hYJFNCHgFuAftdMjmOr2ky1msTT2MZxdwZ6/9PaNz3YyNRPLwOatB6dFvpt3LWOeOH622EgH+UouE4OaeSxTtIqx5oAUTkT82EW9AKLIfDLnW2rFHqrnwCytYZt6KTP0PO2DZpqIsk2XLyLHdz9FuT0yH0kxLcP77th6h1RpGRzxNyazAaG/c7dsSHdR8f5YLvpz9C4lXi+QNnv9AkhhTP+SXQRTg1w915P6yUVZvKRsQfFN/iI7jxbqWjOoc9dZZbun1AC1m28xvYygrXjYQhXptzCfunQQo4lmTCp+JFEnlJVCLd/Xst/FLmFwLNu3vBFDgpfVSSXB+5Ht6EMXIC/u6QvbKhrPlM/8pVMHpYx3t2a4u94HWA=
    # Generate with:
    #   echo -n '<the real password>' | kubeseal --raw --scope strict \
    #     --namespace epg --name epgstation-secrets
    basic-auth-password: AgDT1Q1VOH3e8QktBxG6hmbmjHNVpdhMtjeecLc+5BmR2hSxwhtfLXaNqBbftj/NIT0wK9QnHuj44sZ23MNBZoeJ0PW8ipMbUqCBvntuma9bGP39nasra+R7v5G09GGhytO8xsNm9BXGgtawfarFnOP1PfoHQbePhhBrDlX/UUi/BPNro4exw6E6024fUCgRujfbzxi5CcaU9CvU0Yr2I/estbT+yzM78z9tBYGwJ6YSIOpybP40W70MWr7nLkg+x4ESI8SsQXejkr2Eem1HJHgJKX3kwd37ByGCGTPxwB0u8E9WhdCyXYi/+NgrrV6BA3wr15MMdEFHQpy6PBhm/QGRLxI477QG4rQyBegxo7z5YEx1nOlL/5HLGzm1rWszmlxVpKlfA/vEGtewYCJuTKtTLFCk1CQDWGzGxQKdNiDnonAFAE3zvYkvevzuv2cK3RC0vOJXYcH5I/u2eCPMR+JXh46fNj4o/Pt+FvdD3bk00AsrO+wY863m3oD6QyVHlRMJBp36BO2AGCfM1H04MKtimYmp5LFc2X2dhtOqoyQyeLOUUJoqg0lNtaz/AOlMeqqQ6zIGuZ4NOHR+7+2Uzpw/K2renJgK4RpJ7hGN7ofmFfBCCqGDzcg9HVYyS12XfePG2tM+s2mQe7bPWOnT8LzsB8FNnFAM1e4EsolVGlYGKBLulZ4jc3C4/lw0VoCudg0lfILtfvlYsoMDxP0=
  template:
    metadata:
      name: epgstation-secrets
      namespace: epg
    type: Opaque
