---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: epgstation-secrets
  namespace: epg
spec:
  encryptedData:
    xool-api-key: AgBWdvyTAdXtP/xOutu1jKzS+/o3x7VaatfmCf0PgCrN5YoX/k7HpjZY+YC7iL0pV2CU8bQ82BB3OW1JVB6j75YW2292nfS9roZGGI6lptaHJrVT0mpAYRr170TSADKvlqukiPcNmYLo33FUL/OgNOvjf3uoazi0Xw8LW2upyKIuC57Sbg3rphNWL+RhIlqavOaijNdFqTadvPh8+C3LRGLKSUAvkcJD/WLMf9mflxTybADYpetLer0zPTpcLb4OFZ6ghRwoq4wCsJt1Rvt0qw567Pi81qm8Vx+NmrtdwBIZ05C+U4wj1HtDbkEWZoQ7BGvbv7gvz372pcrFo1CNP+aZVb6KtaVz3pwfu+rZfgcx5dcWJBkZNeJuypFv1hYJFNCHgFuAftdMjmOr2ky1msTT2MZxdwZ6/9PaNz3YyNRPLwOatB6dFvpt3LWOeOH622EgH+UouE4OaeSxTtIqx5oAUTkT82EW9AKLIfDLnW2rFHqrnwCytYZt6KTP0PO2DZpqIsk2XLyLHdz9FuT0yH0kxLcP77th6h1RpGRzxNyazAaG/c7dsSHdR8f5YLvpz9C4lXi+QNnv9AkhhTP+SXQRTg1w915P6yUVZvKRsQfFN/iI7jxbqWjOoc9dZZbun1AC1m28xvYygrXjYQhXptzCfunQQo4lmTCp+JFEnlJVCLd/Xst/FLmFwLNu3vBFDgpfVSSXB+5Ht6EMXIC/u6QvbKhrPlM/8pVMHpYx3t2a4u94HWA=
  template:
    metadata:
      name: epgstation-secrets
      namespace: epg
    type: Opaque
