# Fixed self-signed certificate for e.home.arpa (LAN-only access).
# Not sensitive: this route is restricted to 10.10.0.0/16 and browsers
# already show a certificate warning for it by design. Valid until 2036-07-22.
apiVersion: v1
kind: Secret
metadata:
  name: e-home-arpa-tls
  namespace: epg
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtRENDQVQrZ0F3SUJBZ0lVRUo1eE1wQWVVK0VTN3d4Q3lzWFM1UjlBcS9zd0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXd3TFpTNW9iMjFsTG1GeWNHRXdIaGNOTWpZd056STFNREl4TVRRMldoY05Nell3TnpJeQpNREl4TVRRMldqQVdNUlF3RWdZRFZRUUREQXRsTG1odmJXVXVZWEp3WVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGdmtzdU1rUHhXeXVJQ1dOaG10UXcybEFPdkpqSXIzNnpqTUdJVUlIZWRUYWUyNlJ3eTMKeC9lTmFWRmVBd25SZG5ibncxUmV4L2NkZ1lkZ2NmQjZuNTJqYXpCcE1CMEdBMVVkRGdRV0JCUWVOMVdJK2lrZAptV3lxUXZsdnVPckdZUTUrOGpBZkJnTlZIU01FR0RBV2dCUWVOMVdJK2lrZG1XeXFRdmx2dU9yR1lRNSs4akFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUJZR0ExVWRFUVFQTUEyQ0MyVXVhRzl0WlM1aGNuQmhNQW9HQ0NxR1NNNDkKQkFNQ0EwY0FNRVFDSURWNXNVOHJFZGtxajkxZzJwTGxYTUVWSjRETlFzYW8ydlgyZ2FXRFlhbmJBaUJGRGorTwpvQ1lmeXUrWFB2QktBb0JaRzNHWEc3cmxPVGFxNnAvRFppbWRPdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2RmN3Nrc0xnZ2dObWRnZGsKak1SVU91SG9hZGZvK3l2cExTZnR5UXNlU0lpaFJBTkNBQVJiNUxMakpEOFZzcmlBbGpZWnJVTU5wUURyeVl5Swo5K3M0ekJpRkNCM25VMm50dWtjTXQ4ZjNqV2xSWGdNSjBYWjI1OE5VWHNmM0hZR0hZSEh3ZXArZAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
