port: 8888
socketioPort: 8888
clientSocketioPort: 443
mirakurunPath: http://mirakurun:40772/

dbtype: mysql
mysql:
    host: db
    port: 3306
    user: root
    password: epgstation
    database: epgstation
    charset: utf8mb4

epgUpdateIntervalTime: 10

conflictPriority: 1
recPriority: 2

recordedFormat: '%HALF_WIDTH_TITLE%-%YEAR%%MONTH%%DAY%-%HOUR%%MIN%%SEC%'
recordedFileExtension: .m2ts
recorded:
    - name: recorded
      path: '%ROOT%/recorded'

thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 128

ffmpeg: /usr/local/bin/ffmpeg
ffprobe: /usr/local/bin/ffprobe

encodeProcessNum: 5
concurrentEncodeNum: 5
encode:
    - name: AV1
      cmd: '%NODE% %ROOT%/config/enc.js'
      suffix: .mkv
      rate: 4.0


recordingPrepRecFailedCommand: '%NODE% %ROOT%/config/rec.js failprep'
recordingFailedCommand: '%NODE% %ROOT%/config/rec.js fail'
encodingFinishCommand: '%NODE% %ROOT%/config/rec.js encode'

urlscheme:
    m2ts:
        mac: cvlc://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        win: cvlc://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        android: intent://user:${BASIC_AUTH_PASSWORD}@ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    video:
        mac: cvlc://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        win: cvlc://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://user:${BASIC_AUTH_PASSWORD}@ADDRESS
        android: intent://user:${BASIC_AUTH_PASSWORD}@ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    download:
        ios: PROTOCOL://user:${BASIC_AUTH_PASSWORD}@ADDRESS

stream:
    live:
        ts:
            m2ts:
                - name: raw
                - name: comparess
                  cmd:
                      '%FFMPEG% -y -dual_mono_mode main -i pipe:0
                      -ignore_unknown
                      -map 0:s? -c:s copy
                      -map 0:a -c:a libopus -b:a 256k
                      -vf bwdif
                      -map 0:v -c:v libx265 -preset superfast -crf 26
                      -f mpegts pipe:1'
            m2tsll:
                - name: comparess
                  cmd:
                      '%FFMPEG% -y -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0
                      -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1 -flags +cgop
                      -ignore_unknown
                      -map 0:s? -c:s copy
                      -map 0:a:0 -c:a libopus -b:a 256k
                      -vf bwdif
                      -map 0:v -c:v libx265 -preset superfast -tune zerolatency -crf 26
                      -f mpegts pipe:1'
            webm:
                - name: origin
                  cmd:
                      ''
            mp4:
                - name: origin
                  cmd:
                      ''
            hls:
                - name: origin
                  cmd:
                      ''
    recorded:
        ts:
            webm:
                - name: origin
                  cmd:
                      ''
            mp4:
                - name: origin
                  cmd:
                      ''
            hls:
                - name: origin
                  cmd:
                      '%FFMPEG% -sub_type bitmap -font Rounded%SPACE%M+%SPACE%1m%SPACE%for%SPACE%ARIB -dual_mono_mode main -i pipe:0
                      -threads 0 -ignore_unknown
                      -filter_complex [0:v]bwdif,format=yuv420p[bwdif];[bwdif][0:s:0]overlay[v]
                      -map [v] -c:v libsvtav1 -maxrate 6M -bufsize 12M
                      -map 0:a -c:a libopus -b:a 256k
                      -max_muxing_queue_size 1024
                      -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1 -hls_segment_type fmp4
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.m4s -hls_flags delete_segments
                      -master_pl_name stream%streamNum%.m3u8 %streamFileDir%/stream%streamNum%-child.m3u8'
        encoded:
            webm:
                - name: origin
                  cmd:
                      ''
            mp4:
                - name: origin
                  cmd:
                      ''
            hls:
                - name: origin
                  cmd:
                      '%FFMPEG% -c:v libdav1d -ss %SS% -i %INPUT%
                      -threads 0 -ignore_unknown
                      -filter_complex [0:v][0:s:0]overlay[v]
                      -map [v] -c:v libsvtav1 -maxrate 6M -bufsize 12M
                      -map 0:a -c:a copy
                      -max_muxing_queue_size 1024
                      -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1 -hls_segment_type fmp4
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.m4s -hls_flags delete_segments
                      -master_pl_name stream%streamNum%.m3u8 %streamFileDir%/stream%streamNum%-child.m3u8'
